package vk

type FormatInfo struct {
	Format Format
	// Pixel size in bits
	PixelSize  int
	DXGIFormat uint32
	Aspect     ImageAspectFlags
}

var Formats = map[Format]FormatInfo{

	FORMATR4g4UnormPack8:           FormatInfo{Format: FORMATR4g4UnormPack8, PixelSize: 8, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR4g4b4a4UnormPack16:      FormatInfo{Format: FORMATR4g4b4a4UnormPack16, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB4g4r4a4UnormPack16:      FormatInfo{Format: FORMATB4g4r4a4UnormPack16, PixelSize: 16, DXGIFormat: 115, Aspect: IMAGEAspectColorBit},
	FORMATR5g6b5UnormPack16:        FormatInfo{Format: FORMATR5g6b5UnormPack16, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB5g6r5UnormPack16:        FormatInfo{Format: FORMATB5g6r5UnormPack16, PixelSize: 16, DXGIFormat: 85, Aspect: IMAGEAspectColorBit},
	FORMATR5g5b5a1UnormPack16:      FormatInfo{Format: FORMATR5g5b5a1UnormPack16, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB5g5r5a1UnormPack16:      FormatInfo{Format: FORMATB5g5r5a1UnormPack16, PixelSize: 16, DXGIFormat: 86, Aspect: IMAGEAspectColorBit},
	FORMATA1r5g5b5UnormPack16:      FormatInfo{Format: FORMATA1r5g5b5UnormPack16, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8Unorm:                  FormatInfo{Format: FORMATR8Unorm, PixelSize: 8, DXGIFormat: 61, Aspect: IMAGEAspectColorBit},
	FORMATR8Snorm:                  FormatInfo{Format: FORMATR8Snorm, PixelSize: 8, DXGIFormat: 63, Aspect: IMAGEAspectColorBit},
	FORMATR8Uscaled:                FormatInfo{Format: FORMATR8Uscaled, PixelSize: 8, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8Sscaled:                FormatInfo{Format: FORMATR8Sscaled, PixelSize: 8, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8Uint:                   FormatInfo{Format: FORMATR8Uint, PixelSize: 8, DXGIFormat: 62, Aspect: IMAGEAspectColorBit},
	FORMATR8Sint:                   FormatInfo{Format: FORMATR8Sint, PixelSize: 8, DXGIFormat: 64, Aspect: IMAGEAspectColorBit},
	FORMATR8Srgb:                   FormatInfo{Format: FORMATR8Srgb, PixelSize: 8, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Unorm:                FormatInfo{Format: FORMATR8g8Unorm, PixelSize: 16, DXGIFormat: 49, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Snorm:                FormatInfo{Format: FORMATR8g8Snorm, PixelSize: 16, DXGIFormat: 51, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Uscaled:              FormatInfo{Format: FORMATR8g8Uscaled, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Sscaled:              FormatInfo{Format: FORMATR8g8Sscaled, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Uint:                 FormatInfo{Format: FORMATR8g8Uint, PixelSize: 16, DXGIFormat: 50, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Sint:                 FormatInfo{Format: FORMATR8g8Sint, PixelSize: 16, DXGIFormat: 52, Aspect: IMAGEAspectColorBit},
	FORMATR8g8Srgb:                 FormatInfo{Format: FORMATR8g8Srgb, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Unorm:              FormatInfo{Format: FORMATR8g8b8Unorm, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Snorm:              FormatInfo{Format: FORMATR8g8b8Snorm, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Uscaled:            FormatInfo{Format: FORMATR8g8b8Uscaled, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Sscaled:            FormatInfo{Format: FORMATR8g8b8Sscaled, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Uint:               FormatInfo{Format: FORMATR8g8b8Uint, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Sint:               FormatInfo{Format: FORMATR8g8b8Sint, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8Srgb:               FormatInfo{Format: FORMATR8g8b8Srgb, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Unorm:              FormatInfo{Format: FORMATB8g8r8Unorm, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Snorm:              FormatInfo{Format: FORMATB8g8r8Snorm, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Uscaled:            FormatInfo{Format: FORMATB8g8r8Uscaled, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Sscaled:            FormatInfo{Format: FORMATB8g8r8Sscaled, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Uint:               FormatInfo{Format: FORMATB8g8r8Uint, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Sint:               FormatInfo{Format: FORMATB8g8r8Sint, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8Srgb:               FormatInfo{Format: FORMATB8g8r8Srgb, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Unorm:            FormatInfo{Format: FORMATR8g8b8a8Unorm, PixelSize: 32, DXGIFormat: 28, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Snorm:            FormatInfo{Format: FORMATR8g8b8a8Snorm, PixelSize: 32, DXGIFormat: 31, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Uscaled:          FormatInfo{Format: FORMATR8g8b8a8Uscaled, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Sscaled:          FormatInfo{Format: FORMATR8g8b8a8Sscaled, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Uint:             FormatInfo{Format: FORMATR8g8b8a8Uint, PixelSize: 32, DXGIFormat: 30, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Sint:             FormatInfo{Format: FORMATR8g8b8a8Sint, PixelSize: 32, DXGIFormat: 32, Aspect: IMAGEAspectColorBit},
	FORMATR8g8b8a8Srgb:             FormatInfo{Format: FORMATR8g8b8a8Srgb, PixelSize: 32, DXGIFormat: 29, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Unorm:            FormatInfo{Format: FORMATB8g8r8a8Unorm, PixelSize: 32, DXGIFormat: 87, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Snorm:            FormatInfo{Format: FORMATB8g8r8a8Snorm, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Uscaled:          FormatInfo{Format: FORMATB8g8r8a8Uscaled, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Sscaled:          FormatInfo{Format: FORMATB8g8r8a8Sscaled, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Uint:             FormatInfo{Format: FORMATB8g8r8a8Uint, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Sint:             FormatInfo{Format: FORMATB8g8r8a8Sint, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB8g8r8a8Srgb:             FormatInfo{Format: FORMATB8g8r8a8Srgb, PixelSize: 32, DXGIFormat: 91, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8UnormPack32:      FormatInfo{Format: FORMATA8b8g8r8UnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8SnormPack32:      FormatInfo{Format: FORMATA8b8g8r8SnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8UscaledPack32:    FormatInfo{Format: FORMATA8b8g8r8UscaledPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8SscaledPack32:    FormatInfo{Format: FORMATA8b8g8r8SscaledPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8UintPack32:       FormatInfo{Format: FORMATA8b8g8r8UintPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8SintPack32:       FormatInfo{Format: FORMATA8b8g8r8SintPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA8b8g8r8SrgbPack32:       FormatInfo{Format: FORMATA8b8g8r8SrgbPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2r10g10b10UnormPack32:   FormatInfo{Format: FORMATA2r10g10b10UnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2r10g10b10SnormPack32:   FormatInfo{Format: FORMATA2r10g10b10SnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2r10g10b10UscaledPack32: FormatInfo{Format: FORMATA2r10g10b10UscaledPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2r10g10b10SscaledPack32: FormatInfo{Format: FORMATA2r10g10b10SscaledPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2r10g10b10UintPack32:    FormatInfo{Format: FORMATA2r10g10b10UintPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2r10g10b10SintPack32:    FormatInfo{Format: FORMATA2r10g10b10SintPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2b10g10r10UnormPack32:   FormatInfo{Format: FORMATA2b10g10r10UnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2b10g10r10SnormPack32:   FormatInfo{Format: FORMATA2b10g10r10SnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2b10g10r10UscaledPack32: FormatInfo{Format: FORMATA2b10g10r10UscaledPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2b10g10r10SscaledPack32: FormatInfo{Format: FORMATA2b10g10r10SscaledPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2b10g10r10UintPack32:    FormatInfo{Format: FORMATA2b10g10r10UintPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATA2b10g10r10SintPack32:    FormatInfo{Format: FORMATA2b10g10r10SintPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16Unorm:                 FormatInfo{Format: FORMATR16Unorm, PixelSize: 16, DXGIFormat: 56, Aspect: IMAGEAspectColorBit},
	FORMATR16Snorm:                 FormatInfo{Format: FORMATR16Snorm, PixelSize: 16, DXGIFormat: 58, Aspect: IMAGEAspectColorBit},
	FORMATR16Uscaled:               FormatInfo{Format: FORMATR16Uscaled, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16Sscaled:               FormatInfo{Format: FORMATR16Sscaled, PixelSize: 16, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16Uint:                  FormatInfo{Format: FORMATR16Uint, PixelSize: 16, DXGIFormat: 57, Aspect: IMAGEAspectColorBit},
	FORMATR16Sint:                  FormatInfo{Format: FORMATR16Sint, PixelSize: 16, DXGIFormat: 59, Aspect: IMAGEAspectColorBit},
	FORMATR16Sfloat:                FormatInfo{Format: FORMATR16Sfloat, PixelSize: 16, DXGIFormat: 54, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Unorm:              FormatInfo{Format: FORMATR16g16Unorm, PixelSize: 32, DXGIFormat: 35, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Snorm:              FormatInfo{Format: FORMATR16g16Snorm, PixelSize: 32, DXGIFormat: 37, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Uscaled:            FormatInfo{Format: FORMATR16g16Uscaled, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Sscaled:            FormatInfo{Format: FORMATR16g16Sscaled, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Uint:               FormatInfo{Format: FORMATR16g16Uint, PixelSize: 32, DXGIFormat: 36, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Sint:               FormatInfo{Format: FORMATR16g16Sint, PixelSize: 32, DXGIFormat: 38, Aspect: IMAGEAspectColorBit},
	FORMATR16g16Sfloat:             FormatInfo{Format: FORMATR16g16Sfloat, PixelSize: 32, DXGIFormat: 34, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Unorm:           FormatInfo{Format: FORMATR16g16b16Unorm, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Snorm:           FormatInfo{Format: FORMATR16g16b16Snorm, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Uscaled:         FormatInfo{Format: FORMATR16g16b16Uscaled, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Sscaled:         FormatInfo{Format: FORMATR16g16b16Sscaled, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Uint:            FormatInfo{Format: FORMATR16g16b16Uint, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Sint:            FormatInfo{Format: FORMATR16g16b16Sint, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16Sfloat:          FormatInfo{Format: FORMATR16g16b16Sfloat, PixelSize: 48, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Unorm:        FormatInfo{Format: FORMATR16g16b16a16Unorm, PixelSize: 64, DXGIFormat: 11, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Snorm:        FormatInfo{Format: FORMATR16g16b16a16Snorm, PixelSize: 64, DXGIFormat: 13, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Uscaled:      FormatInfo{Format: FORMATR16g16b16a16Uscaled, PixelSize: 64, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Sscaled:      FormatInfo{Format: FORMATR16g16b16a16Sscaled, PixelSize: 64, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Uint:         FormatInfo{Format: FORMATR16g16b16a16Uint, PixelSize: 64, DXGIFormat: 12, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Sint:         FormatInfo{Format: FORMATR16g16b16a16Sint, PixelSize: 64, DXGIFormat: 14, Aspect: IMAGEAspectColorBit},
	FORMATR16g16b16a16Sfloat:       FormatInfo{Format: FORMATR16g16b16a16Sfloat, PixelSize: 64, DXGIFormat: 10, Aspect: IMAGEAspectColorBit},
	FORMATR32Uint:                  FormatInfo{Format: FORMATR32Uint, PixelSize: 32, DXGIFormat: 42, Aspect: IMAGEAspectColorBit},
	FORMATR32Sint:                  FormatInfo{Format: FORMATR32Sint, PixelSize: 32, DXGIFormat: 43, Aspect: IMAGEAspectColorBit},
	FORMATR32Sfloat:                FormatInfo{Format: FORMATR32Sfloat, PixelSize: 32, DXGIFormat: 41, Aspect: IMAGEAspectColorBit},
	FORMATR32g32Uint:               FormatInfo{Format: FORMATR32g32Uint, PixelSize: 64, DXGIFormat: 17, Aspect: IMAGEAspectColorBit},
	FORMATR32g32Sint:               FormatInfo{Format: FORMATR32g32Sint, PixelSize: 64, DXGIFormat: 18, Aspect: IMAGEAspectColorBit},
	FORMATR32g32Sfloat:             FormatInfo{Format: FORMATR32g32Sfloat, PixelSize: 64, DXGIFormat: 16, Aspect: IMAGEAspectColorBit},
	FORMATR32g32b32Uint:            FormatInfo{Format: FORMATR32g32b32Uint, PixelSize: 96, DXGIFormat: 7, Aspect: IMAGEAspectColorBit},
	FORMATR32g32b32Sint:            FormatInfo{Format: FORMATR32g32b32Sint, PixelSize: 96, DXGIFormat: 8, Aspect: IMAGEAspectColorBit},
	FORMATR32g32b32Sfloat:          FormatInfo{Format: FORMATR32g32b32Sfloat, PixelSize: 96, DXGIFormat: 6, Aspect: IMAGEAspectColorBit},
	FORMATR32g32b32a32Uint:         FormatInfo{Format: FORMATR32g32b32a32Uint, PixelSize: 128, DXGIFormat: 3, Aspect: IMAGEAspectColorBit},
	FORMATR32g32b32a32Sint:         FormatInfo{Format: FORMATR32g32b32a32Sint, PixelSize: 128, DXGIFormat: 4, Aspect: IMAGEAspectColorBit},
	FORMATR32g32b32a32Sfloat:       FormatInfo{Format: FORMATR32g32b32a32Sfloat, PixelSize: 128, DXGIFormat: 2, Aspect: IMAGEAspectColorBit},
	FORMATR64Uint:                  FormatInfo{Format: FORMATR64Uint, PixelSize: 64, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64Sint:                  FormatInfo{Format: FORMATR64Sint, PixelSize: 64, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64Sfloat:                FormatInfo{Format: FORMATR64Sfloat, PixelSize: 64, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64Uint:               FormatInfo{Format: FORMATR64g64Uint, PixelSize: 128, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64Sint:               FormatInfo{Format: FORMATR64g64Sint, PixelSize: 128, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64Sfloat:             FormatInfo{Format: FORMATR64g64Sfloat, PixelSize: 128, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64b64Uint:            FormatInfo{Format: FORMATR64g64b64Uint, PixelSize: 192, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64b64Sint:            FormatInfo{Format: FORMATR64g64b64Sint, PixelSize: 192, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64b64Sfloat:          FormatInfo{Format: FORMATR64g64b64Sfloat, PixelSize: 192, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64b64a64Uint:         FormatInfo{Format: FORMATR64g64b64a64Uint, PixelSize: 256, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64b64a64Sint:         FormatInfo{Format: FORMATR64g64b64a64Sint, PixelSize: 256, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATR64g64b64a64Sfloat:       FormatInfo{Format: FORMATR64g64b64a64Sfloat, PixelSize: 256, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATB10g11r11UfloatPack32:    FormatInfo{Format: FORMATB10g11r11UfloatPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATD16Unorm:                 FormatInfo{Format: FORMATD16Unorm, PixelSize: 16, DXGIFormat: 55, Aspect: IMAGEAspectDepthBit},
	FORMATX8D24UnormPack32:         FormatInfo{Format: FORMATX8D24UnormPack32, PixelSize: 32, DXGIFormat: 0, Aspect: IMAGEAspectDepthBit},
	FORMATD32Sfloat:                FormatInfo{Format: FORMATD32Sfloat, PixelSize: 32, DXGIFormat: 40, Aspect: IMAGEAspectDepthBit},
	FORMATS8Uint:                   FormatInfo{Format: FORMATS8Uint, PixelSize: 8, DXGIFormat: 0, Aspect: IMAGEAspectColorBit},
	FORMATD16UnormS8Uint:           FormatInfo{Format: FORMATD16UnormS8Uint, PixelSize: 24, DXGIFormat: 0, Aspect: IMAGEAspectDepthBit | IMAGEAspectStencilBit},
	FORMATD24UnormS8Uint:           FormatInfo{Format: FORMATD24UnormS8Uint, PixelSize: 32, DXGIFormat: 45, Aspect: IMAGEAspectDepthBit | IMAGEAspectStencilBit},
	FORMATD32SfloatS8Uint:          FormatInfo{Format: FORMATD32SfloatS8Uint, PixelSize: 40, DXGIFormat: 20, Aspect: IMAGEAspectDepthBit | IMAGEAspectStencilBit},
	FORMATBc1RgbUnormBlock:         FormatInfo{Format: FORMATBc1RgbUnormBlock, PixelSize: 4, DXGIFormat: 71, Aspect: IMAGEAspectColorBit},
	FORMATBc1RgbSrgbBlock:          FormatInfo{Format: FORMATBc1RgbSrgbBlock, PixelSize: 4, DXGIFormat: 72, Aspect: IMAGEAspectColorBit},
	FORMATBc1RgbaUnormBlock:        FormatInfo{Format: FORMATBc1RgbaUnormBlock, PixelSize: 4, DXGIFormat: 71, Aspect: IMAGEAspectColorBit},
	FORMATBc1RgbaSrgbBlock:         FormatInfo{Format: FORMATBc1RgbaSrgbBlock, PixelSize: 4, DXGIFormat: 72, Aspect: IMAGEAspectColorBit},
	FORMATBc2UnormBlock:            FormatInfo{Format: FORMATBc2UnormBlock, PixelSize: 8, DXGIFormat: 74, Aspect: IMAGEAspectColorBit},
	FORMATBc2SrgbBlock:             FormatInfo{Format: FORMATBc2SrgbBlock, PixelSize: 8, DXGIFormat: 75, Aspect: IMAGEAspectColorBit},
	FORMATBc3UnormBlock:            FormatInfo{Format: FORMATBc3UnormBlock, PixelSize: 8, DXGIFormat: 77, Aspect: IMAGEAspectColorBit},
	FORMATBc3SrgbBlock:             FormatInfo{Format: FORMATBc3SrgbBlock, PixelSize: 8, DXGIFormat: 78, Aspect: IMAGEAspectColorBit},
	FORMATBc4UnormBlock:            FormatInfo{Format: FORMATBc4UnormBlock, PixelSize: 8, DXGIFormat: 80, Aspect: IMAGEAspectColorBit},
	FORMATBc4SnormBlock:            FormatInfo{Format: FORMATBc4SnormBlock, PixelSize: 8, DXGIFormat: 81, Aspect: IMAGEAspectColorBit},
	FORMATBc5UnormBlock:            FormatInfo{Format: FORMATBc5UnormBlock, PixelSize: 8, DXGIFormat: 83, Aspect: IMAGEAspectColorBit},
	FORMATBc5SnormBlock:            FormatInfo{Format: FORMATBc5SnormBlock, PixelSize: 8, DXGIFormat: 84, Aspect: IMAGEAspectColorBit},
	FORMATBc6hUfloatBlock:          FormatInfo{Format: FORMATBc6hUfloatBlock, PixelSize: 8, DXGIFormat: 95, Aspect: IMAGEAspectColorBit},
	FORMATBc6hSfloatBlock:          FormatInfo{Format: FORMATBc6hSfloatBlock, PixelSize: 8, DXGIFormat: 96, Aspect: IMAGEAspectColorBit},
	FORMATBc7UnormBlock:            FormatInfo{Format: FORMATBc7UnormBlock, PixelSize: 8, DXGIFormat: 98, Aspect: IMAGEAspectColorBit},
	FORMATBc7SrgbBlock:             FormatInfo{Format: FORMATBc7SrgbBlock, PixelSize: 8, DXGIFormat: 99, Aspect: IMAGEAspectColorBit},
}
