//

// Autogenerated file. Do not edit!
package phong

import _ "embed"

//go:generate glslangValidator -V phong.vert.glsl -o phong.vert.spv
//go:generate glslangValidator -V phong.frag.glsl -o phong.frag.spv

//go:embed phong.vert.spv
var phong_vert_spv []byte

//go:embed phong.frag.spv
var phong_frag_spv []byte
